version: '3.8'

services:
  backend:
    build: ./backend
    container_name: synergy-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/movies.json:/app/movies.json
      - ./backend/restaurants.json:/app/restaurants.json

  frontend:
    build: ./frontend
    container_name: synergy-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
